Delete Fortran :D
mantidproject/quickBayes pull request #57
Opened 2023-03-28 16:34 UTC by AnthonyLim23

This PR is removing the old code (Fortran and the direct translation). It also cleans up the code base, removing unused files and renames/restructures the code to suit the new code.

The "help" method of Python also works with the new package
```
>>> help("quickBayes")
Help on package quickBayes:

NAME
    quickBayes

PACKAGE CONTENTS
    fit_engines (package)
    fit_functions (package)
    log_likelihood
    utils (package)
    workflows (package)
```

To test:

see that the release pipieline is working: https://pypi.org/project/quickBayes/1.0.0b3/#history (windows and linux for 1.0.0b3) from this commit https://github.com/mantidproject/quickBayes/pull/57/commits/06e58808b708a8a628ba153f06ac981d48cf682b

Review the code and see that the Fortran is gone

2023-03-29 09:17 UTC, AnthonyLim23 commented
my computer:

version      muon         qldata        qse       quest
c 0.3           0.087          0.349        4.99       72.3

2023-03-29 09:18 UTC, AnthonyLim23 commented
windows build server

```
version              muon                   qldata                qse                 quest
c 0.3                  0.087                    0.349                 4.99                  72.3
```

2023-03-29 09:18 UTC, AnthonyLim23 commented
ubuntu build server

```
version              muon                   qldata                qse                 quest
c 0.3                  0.087                    0.349                 4.99                  72.3
```

2023-03-31 14:15 UTC, SilkeSchomann requested changes
It is nice to see the Fortran code go! I've only found two absolutely minor things.

2023-03-31 14:15 UTC, SilkeSchomann commented on setup.py
> +                'model selection and grid searchs of fits '
```suggestion
                'model selection and grid searches of fits '
```

2023-03-31 14:15 UTC, SilkeSchomann commented on tools/setup_helper.py
> +    """
param filenames is missing in docstrings

2023-03-31 14:24 UTC, AnthonyLim23 commented on tools/setup_helper.py
> +    :param dirname: A relative path to the list of source files
```suggestion
    :param dirname: A relative path to the list of source files
    :param filenames: the names of the source files
```

2023-03-31 14:32 UTC, SilkeSchomann approved these changes

2023-03-31 14:34 UTC, merged

2023-07-11 08:30 UTC, AnthonyLim23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [test two](https://trello.com/c/Lf6KD7ya/4-test-two)