14 mac support
mantidproject/quickBayes pull request #58
Opened 2023-03-30 15:04 UTC by AnthonyLim23

2023-03-31 14:40 UTC, AnthonyLim23 commented on setup.py
> +                'model selection and grid searchs of fits '
```suggestion
                'model selection and grid searches of fits '
```

2023-04-03 08:31 UTC, robertapplin requested changes
Looks good. Just spotted a couple of typos

2023-04-03 08:31 UTC, robertapplin commented on README.md
> +The package will automatically be uploaded when a relase is created in github, see [here](https://cibuildwheel.readthedocs.io/en/stable/options/) for the details.
```suggestion
The package will automatically be uploaded when a release is created in Github, see [here](https://cibuildwheel.readthedocs.io/en/stable/options/) for the details.
```

2023-04-03 08:31 UTC, robertapplin commented on README.md
> +To create the environment run the command from the root directory of the project:
```suggestion
To create the environment run this command from the root directory of the project:
```

2023-04-03 08:39 UTC, robertapplin approved these changes
Thanks for the changes, looks good to me

2023-04-03 08:56 UTC, merged