Add basic parallel processing
mantidproject/quickBayes pull request #68
Opened 2023-07-17 08:50 UTC by AnthonyLim23

2023-07-20 15:53 UTC, RichardWaiteSTFC requested changes
Looks good, thanks for the nice documentation (one small typo sorry!). It seems to be a very versatile way of using multiple threads to parallelise loops.

I had a question about the use of prefer over hard-coding the backend - but that's just for my understanding!

2023-07-20 15:53 UTC, RichardWaiteSTFC commented on docs/source/dev/parallel.rst
> +It is important to note that the method call is to a wrapper of themethod function we want to run in parallel.
Typo `the method`

2023-07-20 15:53 UTC, RichardWaiteSTFC commented on setup.py
> +VERSION = "1.0.0b12"
Incremented version by 2, or am I missing something?

2023-07-20 15:53 UTC, RichardWaiteSTFC commented on src/quickBayes/utils/parallel.py
> +                    prefer="threads")(delayed(function)(j) for j in items)
Is there any reason not to specify `backend=threading`?

2023-07-21 09:53 UTC, AnthonyLim23 commented on docs/source/dev/parallel.rst
> +It is important to note that the method call is to a wrapper of themethod function we want to run in parallel.
```suggestion
It is important to note that the method call is to a wrapper of the method function we want to run in parallel.
```

2023-07-21 09:53 UTC, AnthonyLim23 commented on setup.py
> +VERSION = "1.0.0b12"
I pushed 2 versions (the first was using the default and the second was using threading)

2023-07-21 09:54 UTC, AnthonyLim23 commented on src/quickBayes/utils/parallel.py
> +                    prefer="threads")(delayed(function)(j) for j in items)
I dont really understand it (not looked into it in detail). But the default is to not use threading and instead it does something with the Python console (thats why it doesnt work in mantid)

2023-07-21 11:02 UTC, merged