Docs
mantidproject/quickBayes pull request #75
Opened 2023-10-19 13:12 UTC by AnthonyLim23

2023-10-31 10:18 UTC, jess-farmer requested changes
Looks great - just a couple of very minor comments

2023-10-31 10:18 UTC, jess-farmer commented on docs/source/fitting/fit_engines.rst
> +The :code:`GoFitEngine` uses the :code:`multistart` method from GoFit.
May be worth adding a link here to the GoFit repo/docs?

2023-10-31 10:18 UTC, jess-farmer commented on docs/source/fitting/fit_functions.rst
> +In quickBayes the fit functions are all classes with a very specific structure, see <insert link> for a full list of currently available options.
Missing link needs adding in here

2023-10-31 10:18 UTC, jess-farmer commented on docs/source/fitting/fit_functions.rst
> +  [1.0, 2.0, 3.0]
Should this be `[1.0, 0, 2.0]`?

2023-10-31 10:18 UTC, jess-farmer commented on docs/source/loglikelihood.rst
> +where :math:`\\beta = (x_{max}-x_{min})A_{max}`, :math:`H` is the Hessian matrix.
```suggestion
where :math:`\beta = (x_{max}-x_{min})A_{max}`, :math:`H` is the Hessian matrix.
```
There's a couple of points on this page where there's an extra backslash and math symbols are being shown as words

2023-10-31 10:18 UTC, jess-farmer commented on docs/source/workflows/workflows.rst
> +It inherits the the :code:`workflowTemplate` class but has as additional property :code`get_parameters_and_errors`.
```suggestion
It inherits the the :code:`workflowTemplate` class but has as additional property :code:`get_parameters_and_errors`.
```

2023-10-31 10:18 UTC, jess-farmer commented on docs/source/history.rst
> +The quickBayes method provides FWHM results that are comparable for all :math:`Q` values (green and black data), unlike the original code that has a divergence for low :math`Q` value.
```suggestion
The quickBayes method provides FWHM results that are comparable for all :math:`Q` values (green and black data), unlike the original code that has a divergence for low :math:`Q` value.
```

2023-11-06 10:29 UTC, AnthonyLim23 commented on docs/source/fitting/fit_engines.rst
> +The :code:`GoFitEngine` uses the :code:`multistart` method from GoFit.
```suggestion
The :code:`GoFitEngine` uses the :code:`multistart` method from `GoFit <https://ralna.github.io/GOFit/_build/html/index.html>`.
```

2023-11-06 10:34 UTC, AnthonyLim23 commented on docs/source/fitting/fit_functions.rst
> +In quickBayes the fit functions are all classes with a very specific structure, see <insert link> for a full list of currently available options.
```suggestion
In quickBayes the fit functions are all classes with a very specific structure, see :ref:`here<quickBayes.fit_functions
>` for a full list of currently available options.
```

2023-11-06 10:35 UTC, AnthonyLim23 commented on docs/source/fitting/fit_functions.rst
> +  [1.0, 2.0, 3.0]
```suggestion
  [1.0, 0.0, 2.0]
```

2023-11-06 10:36 UTC, AnthonyLim23 commented on docs/source/loglikelihood.rst
> +The :math:`\\beta` value represents the variation in the data by taking the product of the length of the :math:`x` range with the maximum height of the data.
```suggestion
The :math:`\beta` value represents the variation in the data by taking the product of the length of the :math:`x` range with the maximum height of the data.
```

2023-11-06 10:36 UTC, AnthonyLim23 commented on docs/source/loglikelihood.rst
> +To convert the probability into a loglikelihood we need to take the :math:`\\log_{10}` and use:
```suggestion
To convert the probability into a loglikelihood we need to take the :math:`\log_{10}` and use:
```

2023-11-06 13:33 UTC, jess-farmer approved these changes

2023-11-06 14:10 UTC, merged